### ISSUE TITLE
Unbearably Small

### ISSUE THREAD

**Issue by gopar** [fourier/idea-darkula-theme#1]
Installed and loaded the theme manually `load-theme`. Once loaded, everything became **really** small (text, minibuffer, etc). Would provide picture, but it would just look like a blank screen, since text is barely visible. Didn't really spent time tracking what's going on.

Emacs 24.5 and 24.4

**Comment by fourier** [comment]
Hm, very strange. try to run

``` elisp
(defadvice load-theme (before theme-dont-propagate activate)
 (mapcar #'disable-theme custom-enabled-themes))
```

before (load-theme 'idea-darkula t)
Here is what I got with Emacs -q

<img width="629" alt="screen shot 2015-12-10 at 20 06 56" src="https://cloud.githubusercontent.com/assets/900250/11725357/a20f5314-9f79-11e5-80fb-1710b2c3e34f.png">

**Comment by gopar** [comment]
Followed what you said. Still same result. 

One thing to mentioned is that I built emacs from source. Just of the bat, some flag might of not been configured or something.

**Comment by fourier** [comment]
I cannot reproduce it with "emacs -q" and therefore could not help there, sorry

**Comment by gopar** [comment]
No problem. Feel free the close this issue. It's probably something with my specific setup. Thanks for trying to help \o/

**Comment by fourier** [comment]
Sorry what I couldn't help with it. Probably the official Emacs version(from packages) would help, I don't know. Is it only with this theme and others work fine ?

**Comment by gopar** [comment]
Yups only with this theme. Every other theme works fine.

**Comment by fourier** [comment]
Try to update it in MELPA,  I removed the font-height few day ago, maybe it will help? I can't find anything else in this theme font-related.

**Comment by gopar** [comment]
Yes! That fixed it. Thanks :D

**Comment by fourier** [comment]
Good! Enjoy :) It is my favorite theme right now :)
