### ISSUE TITLE
Font style

### ISSUE THREAD

**Issue by tomasjura** [fourier/idea-darkula-theme#2]
Please remove the font `:family` and `:foundry` setup for the default face. 

``` lisp
(custom-theme-set-faces
 'idea-darkula
 '(default ((t (:family "default"
                        :foundry "default"
                        :underline nil
                        :overline nil
```

Such famlily/foundry setup breaks the font on systems which do not have a "default" font alias. Tested on windows.

**Comment by fourier** [comment]
Please verify if it works for you.

**Comment by tomasjura** [comment]
Yes it works, I have this implemented in my local package for some time. Thanks.
